version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
  backend:
    container_name: goweb
    build: .
    ports:
      - '55000:55000'
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db: