version: "3.8"
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 12345
    ports:
      - "5436:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    container_name: goweb
    build: .
    ports:
      - '55000:55000'
    env_file:
      - env.env
    depends_on:
      - db

volumes:
  db:
networks:
  db:
    driver: bridge